#!/usr/bin/env sh

# Run lint-staged
echo "🧹 Running linting and tests..."
pnpm exec lint-staged

# Se lint-staged falhar, aborta o commit
if [ $? -ne 0 ]; then
  echo "❌ Pre-commit checks failed. Aborting commit."
  exit 1
fi